--CREATE SCHEMA IF NOT EXISTS testdb;

CREATE TABLE IF NOT EXISTS SERVER_USER(

EMAIL VARCHAR(250) PRIMARY KEY,
FIRSTNAME VARCHAR(250) ,
SURNAME VARCHAR(250) ,
USERNAME VARCHAR(250),
PASSWORD VARCHAR(250),
WEIGHT_STONE INT,
WEIGHT_POUNDS INT,
HEIGHT DOUBLE,
GENDER VARCHAR(10)

);